### ISSUE TITLE
Lỗi khi run lệnh: mvn clean verify -Dtags="register"

### ISSUE THREAD

**Issue by wizardsconan** [wizardsconan/Senerity-BDD#2]
Em đang học bài Bài #30: Chỉnh sửa cấu hình của WebDriver ( Custome WebDriver) .
Sau khi em thực hiện đúng theo video sau khi chạy lệnh : mvn clean verify -Dtags="register".
thì nó báo lỗi như dưới ạ.
C:\Users\hiennt26\eclipse-workspace\webui-automation>mvn clean verify -Dtags="register"
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< vn.amabay:webui-automation >---------------------
[INFO] Building Serenity project with JUnit and WebDriver 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ webui-automation ---
[INFO] Deleting C:\Users\hiennt26\eclipse-workspace\webui-automation\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ webui-automation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\hiennt26\eclipse-workspace\webui-automation\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ webui-automation ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ webui-automation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ webui-automation ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 15 source files to C:\Users\hiennt26\eclipse-workspace\webui-automation\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ webui-automation ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ webui-automation ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: C:\Users\hiennt26\eclipse-workspace\webui-automation\target\webui-automation-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-failsafe-plugin:2.19.1:integration-test (default) @ webui-automation ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running vn.amabay.features.browser.WhenOpenLinkTheWeb
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener -

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   /
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|

 News and tutorials at http://www.serenity-bdd.info
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/
 Join the Serenity Community on Rocket Chat at https://serenity-bdd.rocket.chat
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport
 Learn Serenity BDD online at http://serenity-dojo.com
-------------------------------------------------------------------------------------

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.626 sec - in vn.amabay.features.browser.WhenOpenLinkTheWeb
Running vn.amabay.features.register.WhenRegisterNewAccount
[main] WARN net.thucydides.core.pages.Pages - Failed to instantiate page of type class vn.amabay.pages.HomePage ({})
java.lang.RuntimeException: Could not instantiate the custom webdriver provider of type vn.amabuy.customedriver.MyCustomeDriver
        at net.thucydides.core.webdriver.ProvidedDriverConfiguration.getDriverSource(ProvidedDriverConfiguration.java:47)
        at net.thucydides.core.webdriver.WebDriverFacade.getDriverClass(WebDriverFacade.java:94)
        at net.thucydides.core.webdriver.WebDriverType.isMobile(WebDriverType.java:9)
        at net.thucydides.core.webdriver.ElementLocatorFactorySelector.platformFor(ElementLocatorFactorySelector.java:48)
        at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:41)
        at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:31)
        at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:21)
        at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:19)
        at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:166)
        at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:170)
        at net.thucydides.core.pages.Pages.createFromSimpleConstructor(Pages.java:237)
        at net.thucydides.core.pages.Pages.getCurrentPageOfType(Pages.java:204)
        at net.thucydides.core.pages.Pages.getPage(Pages.java:90)
        at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:55)
        at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
        at net.thucydides.core.steps.StepFactory.injectOtherDependenciesInto(StepFactory.java:166)
        at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:156)
        at net.thucydides.core.steps.StepFactory.instantiateNewStepLibraryFor(StepFactory.java:139)
        at net.thucydides.core.steps.StepFactory.getNewStepLibraryFor(StepFactory.java:86)
        at net.thucydides.core.steps.IndividualInstancesByDefaultStepCreationStrategy.initiateStepsFor(IndividualInstancesByDefaultStepCreationStrategy.java:16)
        at net.thucydides.core.steps.StepAnnotations.instantiateAnyUnitiaializedSteps(StepAnnotations.java:76)
        at net.thucydides.core.steps.StepAnnotations.instanciateScenarioStepFields(StepAnnotations.java:60)
        at net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(StepAnnotations.java:42)
        at net.serenitybdd.junit.runners.SerenityRunner.injectScenarioStepsInto(SerenityRunner.java:636)
        at net.serenitybdd.junit.runners.SerenityRunner.methodInvoker(SerenityRunner.java:599)
        at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:273)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:463)
        at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:438)
        at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:45)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:242)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: When register new account
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener -
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/

TEST STARTED: Initialisation
-------------------------------------------------------------------
[main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
[pool-3-thread-1] INFO net.thucydides.core.requirements.PackageRequirementsTagProvider - Loading requirements from package requirements at: vn.amabay.features
[pool-4-thread-1] INFO net.thucydides.core.requirements.PackageRequirementsTagProvider - Loading requirements from package requirements at: vn.amabay.features
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.525 sec <<< FAILURE! - in vn.amabay.features.register.WhenRegisterNewAccount
vn.amabay.features.register.WhenRegisterNewAccount  Time elapsed: 0.571 sec  <<< FAILURE!
net.thucydides.core.pages.WrongPageError:
The page object class vn.amabay.pages.HomePage looks dodgy:
Failed to instantiate page (java.lang.RuntimeException: Could not instantiate the custom webdriver provider of type vn.amabuy.customedriver.MyCustomeDriver)

Running vn.amabay.features.WhenSoftAssert
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in vn.amabay.features.WhenSoftAssert

Results :

Failed tests:
  WhenRegisterNewAccount.vn.amabay.features.register.WhenRegisterNewAccount The page object class vn.amabay.pages.HomePage looks dodgy:
Failed to instantiate page (java.lang.RuntimeException: Could not instantiate the custom webdriver provider of type vn.amabuy.customedriver.MyCustomeDriver)

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO]
[INFO] --- serenity-maven-plugin:2.0.66:aggregate (serenity-reports) @ webui-automation ---
[INFO] current_project.base.dir: C:\Users\hiennt26\eclipse-workspace\webui-automation
[INFO] Generating test results for 0 tests
[INFO] Loading requirements from tag providers :[net.thucydides.core.requirements.PackageRequirementsTagProvider@7e3ee128, net.thucydides.core.requirements.FileSystemRequirementsTagProvider@166ce247]
[INFO] Loading requirements from package requirements at: vn.amabay.features
[INFO] LOADED REQUIREMENTS:
REQUIREMENTS:
    - feature : Browser {id: Browser, displayName: 'Browser', path: , parent: 'null'}
        - story : When open link the web {id: When open link the web, displayName: 'When open link the web', path: browser, parent: 'Browser'}
    - feature : Register {id: Register, displayName: 'Register', path: , parent: 'null'}
        - story : When register new account {id: When register new account, displayName: 'When register new account', path: register, parent: 'Register'}
    - feature : When soft assert {id: When soft assert, displayName: 'When soft assert', path: , parent: 'null'}

[INFO] 5 requirements loaded after 782 ms
[INFO] 0 related requirements found after 782 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports after 829 ms
[INFO] Configured report threads: 20
[INFO] Test results for 0 tests generated in 1.5 secs
[INFO]
[INFO] --- maven-failsafe-plugin:2.19.1:verify (default) @ webui-automation ---
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.809 s
[INFO] Finished at: 2019-08-23T11:42:52+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (default) on project webui-automation: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\hiennt26\eclipse-workspace\webui-automation\target\failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by wizardsconan** [comment]
Done
